### ISSUE TITLE
pearl: Reddit Frontend

### ISSUE THREAD

**Issue by aero31aero** [crux-bphc/fest-manager#279]
Just calling it Reddit Frontend because that was the initial idea. To not make things too tough, the idea proceeds like this:

## Description

There's a JSON file containing an array of entries for a slideshow, in random order, where each entry looks like:

```js
{
  image: "https://image-url-here.png",
  person: "Photographer's Name Here",
  profilepic: "https://small-thumbnail-of-the-photographer.png",
  location: "Location String to be displayed",
  tagline: "A one sentence describing the adventure.",
  description: "Slightly larger description here",
  url: "Leads back to more info about the photographer or the place or whatever."
}
```

Put the JSON file in /public/static/data/slideshow.json. These can be populated by images from /r/travel as well as by our own photog members. That'll be done manually.

All the images are to be displayed with a black overlay and pearl logo on top, and the image metadata displayed at the bottom left. The images shall use the slight scroll effect as in this page here: https://wiki.bits-hyd.org/login 

The first image will be hardcoded, and stored on the server. The subsequent images will be randomly fetched from that file and displayed. Each image should first be preloaded into memory and then displayed for best view.

## Subtasks

- [x] Make sample JSON file with data for testing from lorem pixel or something.
- [ ] Add jade and css to display the metadata on the homepage.
- [ ] Add css/js to show that sliding effect on the background image.
- [ ] Add JS for the core slideshow. More details on this later.
- [ ] Make the logo, timer and contact info extremely transparent, and show them on hover.
- [ ] Add JS to make sure that the above transparency kicks in when the main slideshow starts. the initial look should show the Pearl logo prominently.
- [ ] Whatever remains now. Polish the stuff.
- [ ] Release.

**Comment by FoolDresden** [comment]
I can do the JSON dummy. That ok?

**Comment by Abhideep-Tripathy** [comment]
I take the sliding effect.

**Comment by FoolDresden** [comment]
I'll do the Logo one.

**Comment by aero31aero** [comment]
Done, but overridden. Completed either way.
