### ISSUE TITLE
pearl: Sidebar needs attention

### ISSUE THREAD

**Issue by aero31aero** [crux-bphc/fest-manager#283]
A lot of stuff about the sidebar needs fixing, including:

## Subtasks

- [ ] Sliding in and out on small displays.
- [ ] The sub menu is not centered but main menu is.
- [ ] The sub menu architecture. Make it appear in between the main menu.
- [ ] Other random fixes, if any.

Assigning 1 and 3 to @rogeredthat because he's the only one capable of doing that as of now.

**Comment by rogeredthat** [comment]
Is this over?

**Comment by aero31aero** [comment]
See the third point. I'll do a rough JS version PR and leave the CSS to you, I guess.

If its a WONTFIX then we'll just close it.
